### ISSUE TITLE
Please list the corp name and alliance name in "Involved" page

### ISSUE THREAD

**Issue by 0mza987** [maullerz/breport#5]
First time to use this br tool and it can be easily the best br tool that are still available now. Thanks for you effort, but I have a suggestion to make it a better one.

![image](https://user-images.githubusercontent.com/2572521/59487734-19380200-8eb0-11e9-9ef0-02d20c9669d8.png)

Here we can see the corp and alliance logo but no name displayed.
The purpose is to calculate how many members of a particular corp got involved in this fight, if the corp names got displayed then I can search this corp name in Chrome and i can see the numbers.

Otherwise could you pls add this kind of info on the two sides of the page? I see there are quite some blank spaces

**Comment by maullerz** [comment]
Hi, have some thoughts about that, something like view on adashboard
![image](https://user-images.githubusercontent.com/5295025/59504188-14248400-8eab-11e9-8e22-97a36ac7ca19.png)

I think this would be another one tab - "Composition" for example

**Comment by 0mza987** [comment]
Sure this is a way to show corp members number and it has its own pros and cons.
For pros, it show corp info in a straightforward way and has a participation rank which is good.
But for cons, its kinda hard for viewers to know which side in the br this corp belongs, it requires ppl to be familiar with all big and small groups involved.

Thats just some thoughts from a random user so it's up to you which way to be chosen all both lol. Anyway, thanks for listening and keep up the good works. o7

**Comment by maullerz** [comment]
I hope it suits most of whishes.

<img width="646" alt="Screenshot 2019-06-16" src="https://user-images.githubusercontent.com/5295025/59563563-71077200-9044-11e9-955a-2411068a73dc.png">
